services:
  ochlos:
    build:
      context: .
      dockerfile: Dockerfile
    image: ochlos-attacker:latest
    container_name: ochlos-attacker
    working_dir: /app
    volumes:
      - .:/app
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      - external_net

networks:
  external_net:
    external: true
    name: bartimaeus_app_1_external_net
